import turtle
tao = turtle.pen()
tao = turtle.Turtle()
tao.clear()
tao.penup()
tao.goto(150, -200)

for i in range(2):
    tao.left(90)
    tao.pensize(5)
    tao.pendown()
    tao.forward(400)
    tao.left(90)
    tao.forward(300)

tao.penup()
tao.home()
tao.pensize(3)
tao.goto(0, -20)
tao.pendown()
tao.color("red")
tao.circle(20, 360)
tao.penup()
tao.home()
tao.pendown()
tao.dot(25, "red")

for i in range(10):
    tao.color("red")
    tao.penup()
    tao.forward(30)
    tao.pendown()
    tao.circle(10, 360)
    tao.penup()
    tao.backward(30)
    tao.left(36)

tao.penup()
tao.goto(-110, -200)
tao.left(90)

for i in range(2):
    for i in range(2):
        tao.pendown()
        tao.color("black")
        tao.forward(17)
        tao.left(90)
        tao.color("black")
        for i in range(2):
            tao.forward(15)
            tao.right(90)
            tao.forward(25)
            tao.right(90)
            tao.forward(15)

        tao.right(90)
        tao.penup()
        tao.forward(25)
        tao.pendown()
        tao.forward(15)
        tao.penup()
        tao.forward(15)
        tao.pendown()
        tao.dot(30, "red")
        tao.penup()
        tao.forward(15)

    tao.pendown()
    tao.forward(15)
    tao.color("green")
    tao.right(90)
    for i in range(2):   
        tao.forward(15)
        tao.left(90)
        tao.forward(25)
        tao.left(90)
        tao.forward(15)

    tao.left(90)
    tao.penup()
    tao.forward(25)
    tao.color("black")
    tao.pendown()
    tao.forward(15)
    tao.penup()
    tao.forward(15)
    tao.pendown()
    tao.dot(30, "red")
    tao.penup()
    tao.forward(15)

    tao.pendown()
    tao.color("black")
    tao.forward(15)
    tao.left(90)
    tao.color("black")
    for i in range(2):
        tao.forward(15)
        tao.right(90)
        tao.forward(25)
        tao.right(90)
        tao.forward(15)

    tao.right(90)
    tao.penup()
    tao.forward(25)
    tao.pendown()
    tao.forward(15)
    tao.penup()
    tao.forward(15)
    tao.pendown()
    tao.dot(30, "red")
    tao.penup()
    tao.forward(15)

    tao.pendown()
    tao.color("black")
    tao.forward(15)
    tao.left(90)
    tao.color("black")
    for i in range(2):
        tao.forward(15)
        tao.right(90)
        tao.forward(25)
        tao.right(90)
        tao.forward(15)
    tao.right(90)
    tao.penup()
    tao.forward(25)
    tao.pendown()
    tao.forward(17)
    tao.penup()
    tao.goto(110, -200)
tao.home()

tao.goto(-150, -170)
tao.pendown()
tao.forward(25)
tao.penup()
tao.goto(-150, -82)
tao.pendown()
tao.forward(25)
tao.penup()
tao.goto(-150, 0) 
tao.pendown()
tao.forward(25)
tao.penup()
tao.goto(-150, 85) 
tao.pendown()
tao.forward(25)
tao.penup()
tao.goto(-150, 172) 
tao.pendown()
tao.forward(25)
tao.penup()
tao.home()

tao.goto(125, 170)
tao.pendown()
tao.forward(25)
tao.penup()
tao.goto(125, 82)
tao.pendown()
tao.forward(25)
tao.penup()
tao.goto(125, 0) 
tao.pendown()
tao.forward(25)
tao.penup()
tao.goto(125, -85) 
tao.pendown()
tao.forward(25)
tao.penup()
tao.goto(125, -172) 
tao.pendown()
tao.forward(25)
tao.penup()
tao.home()

tao.goto(0, -200)
tao.left(90)
for i in range(2):
    tao.pendown()
    tao.forward(15)
    tao.penup()
    tao.home()
    tao.goto(0, 200)
    tao.right(90)
tao.penup()
tao.home()

tao.goto(-95, -170) 
for i in range(2):
    tao.pendown()
    tao.forward(20)
    tao.penup()
    tao.forward(15)
    tao.pendown()
    tao.dot(30, "red")
    tao.penup()
    tao.forward(15)
    tao.color("black")
    tao.pendown()
    tao.forward(20)
    tao.color("green")
    tao.right(90)
    for i in range(2):
        tao.forward(15)
        tao.left(90)
        tao.forward(50)
        tao.left(90)
        tao.forward(15)
    tao.left(90)
    tao.penup()
    tao.forward(50)
    tao.color("black")
    tao.pendown()
    tao.forward(20)
    tao.penup()
    tao.forward(15)
    tao.pendown()
    tao.dot(30, "red")
    tao.penup()
    tao.forward(15)
    tao.pendown()
    tao.forward(20)
    tao.penup()
    tao.home()
    tao.goto(-95, 172)
tao.penup()
tao.home()

tao.goto(71, -177)
tao.left(90)
for i in range(2): 
    tao.pendown()
    tao.color("red")
    tao.circle(70, 180)
    tao.penup()
    tao.home()
    tao.goto(-71 ,177)
    tao.right(90)
tao.penup()
tao.home()

tao.backward(65)
tao.color("red")
tao.goto(-95, -125)
tao.pendown()
tao.forward(44)
tao.circle(30, 130)
tao.dot(30, "red")
tao.circle(100, 58)
tao.penup()
tao.home()
tao.goto(-95, 125)
tao.pendown()
tao.forward(42)
tao.circle(-30, 130)
tao.dot(30, "red")
tao.circle(-100, 58)
tao.penup()
tao.home()

tao.backward(65)
tao.color("red")
tao.goto(95, -125)
tao.pendown()
tao.backward(44)
tao.circle(30, -130)
tao.dot(30, "red")
tao.circle(100, -58)
tao.penup()
tao.home()
tao.goto(95, 125)
tao.pendown()
tao.left(180)
tao.forward(42)
tao.circle(30, 130)
tao.dot(30, "red")
tao.circle(100, 58)
tao.penup()
tao.home()

tao.right(90)
for i in range(2):
    tao.pendown()
    tao.forward(20)
    tao.penup()
    tao.forward(22)
    tao.pendown()
    tao.forward(85)
    tao.dot(30)
    tao.penup()
    tao.home()
    tao.left(90)
tao.penup()
tao.home()

for i in range(2):
    tao.forward(12)
    tao.pendown()
    tao.forward(53)
    tao.dot(30)
    tao.forward(28)
    tao.penup()
    tao.home()
    tao.left(180)
tao.penup()
tao.home()

tao.goto(-18 , 75)
tao.color("red")
for i in range(2):
    tao.pendown()
    tao.forward(40)
    tao.penup()
    tao.goto(-18 ,-75)
tao.penup()
tao.home()

tao.goto(-66 , -125)
tao.color("red")
for i in range(2):
    tao.left(90)
    tao.pendown()
    tao.forward(250)
    tao.penup()
    tao.home()
    tao.goto(66 ,-125)
tao.penup()
tao.home()



